"""Updating Cart Schema

Revision ID: 1e42439a6e77
Revises: 
Create Date: 2021-05-19 21:54:51.629746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e42439a6e77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('firstName', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('lastName', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('phoneNumber', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('phoneNumber')
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
