"""Added Company/Organisation Column to Cart Table

Revision ID: 53c8a220875c
Revises: da46d6fa988b
Create Date: 2021-05-22 02:14:48.029433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c8a220875c'
down_revision = 'da46d6fa988b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('company')

    # ### end Alembic commands ###
