"""Added pincode to Cart Table

Revision ID: 7b7e4bdaf6b6
Revises: 53c8a220875c
Create Date: 2021-05-24 11:13:03.721784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7e4bdaf6b6'
down_revision = '53c8a220875c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pincode', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('pincode')

    # ### end Alembic commands ###
