"""Added checkout Time

Revision ID: da46d6fa988b
Revises: 1e42439a6e77
Create Date: 2021-05-21 16:28:46.186552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da46d6fa988b'
down_revision = '1e42439a6e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkoutTime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('checkoutTime')

    # ### end Alembic commands ###
